import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import HeaderComponent from "@/components/HeaderComponent";
import FooterComponent from "@/components/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />
        <div className={inter.className} id="layout">{children}</div>
        <FooterComponent />
      </body>
    </html>
  );
}
